{
 "title": "Baremetal / Views / Global",
 "tags": [
  "baremetal",
  "fleet"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "diskdevices",
    "query": "[a-z]+|sda[0-9]+n[0-9]+|sdb[0-9]+"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Pressure (cluster)",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(rate(node_pressure_memory_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(rate(node_pressure_io_waiting_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "I/O"
    },
    {
     "expr": "sum(rate(node_pressure_irq_stalled_seconds_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "CPU Usage (cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * (1 - ((node_memory_MemAvailable_bytes{job=\"$job\"} or node_memory_MemFree_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network - Receive & Transmit (cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"en.*|copper.*|fiber.*\", job=\"$job\"}[$__rate_interval])*8 > 0)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"en.*|copper.*|fiber.*\", job=\"$job\"}[$__rate_interval])*8 > 0)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk Throughput (cluster)",
   "type": "stat",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=~\"$diskdevices\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"$diskdevices\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Wait Time (cluster)",
   "type": "stat",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total[$__rate_interval]) / rate(node_disk_reads_completed_total[$__rate_interval]) > 0)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total[$__rate_interval]) / rate(node_disk_writes_completed_total[$__rate_interval]) > 0)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "System Load (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (instance) (node_load1{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (100 * (1 - ((node_memory_MemAvailable_bytes{job=\"$job\"} or node_memory_MemFree_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware Temperature (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (node_hwmon_temp_crit_celsius{job=\"$job\"})",
     "legendFormat": "{{instance}} - Critical"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "description": "Number of network packets received and transmitted per second, by interface.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_packets_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - rx"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_packets_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - tx"
    }
   ]
  },
  {
   "title": "Network I/O - Throughput (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval])*8)",
     "legendFormat": "{{instance}} - rx"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval])*8)",
     "legendFormat": "{{instance}} - tx"
    }
   ]
  },
  {
   "title": "Network I/O - Saturation (by host)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval])) * 8 / 1000000000 * 100",
     "legendFormat": "{{instance}} - rx"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{device=~\"en.*|copper.*|fiber.*\",job=\"$job\"}[$__rate_interval])) * 8 / 1000000000 * 100",
     "legendFormat": "{{instance}} - tx"
    }
   ]
  },
  {
   "title": "Disk Wait Time (by host)",
   "type": "timeseries",
   "description": "Average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_read_time_seconds_total{job=\"$job\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{job=\"$job\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{instance}} - {{device}} - read"
    },
    {
     "expr": "sum by (instance, device) (rate(node_disk_write_time_seconds_total{job=\"$job\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{job=\"$job\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{instance}} - {{device}} - write"
    }
   ]
  },
  {
   "title": "Disk IOps (by host)",
   "type": "timeseries",
   "description": "Disk I/O operations per second for each device",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_reads_completed_total{device=~\"sd.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{device}} - read"
    },
    {
     "expr": "sum by (instance, device) (rate(node_disk_writes_completed_total{device=~\"sd.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput (by host)",
   "type": "timeseries",
   "description": "Disk I/O throughput per device",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_disk_read_bytes_total{device=~\"sd.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{device}} - read"
    },
    {
     "expr": "sum by (instance, device) (rate(node_disk_written_bytes_total{device=~\"sd.*\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{device}} - write"
    }
   ]
  },
  {
   "title": "Disk Usage % (by host)",
   "type": "timeseries",
   "description": "Average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (device, instance) (100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\", device=~\"/dev/sd.*\", job=\"$job\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\", device=~\"/dev/sd.*\", job=\"$job\"}))",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  }
 ]
}