# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };

  boot.initrd.luks.devices."enc-nixroot".device = "/dev/disk/by-label/CRYPT_NIXROOT";

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc-home".device = "/dev/disk/by-label/CRYPT_HOME";

  fileSystems."/home" =
    {
      device = "/dev/disk/by-label/HOME";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc-backup".device = "/dev/disk/by-label/CRYPT_BACKUP";

  fileSystems."/backup" =
    {
      device = "/dev/disk/by-label/BACKUP";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."enc-swap".device = "/dev/disk/by-label/CRYPT_SWAP";

  swapDevices = [{
    device = "/dev/disk/by-label/SWAP";
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
